---
- name: Create the tibber_exporter group
  ansible.builtin.group:
    name: "{{ tibber_exporter_system_group }}"
    state: present
    system: true
  when: tibber_exporter_system_group != "root"

- name: Create the tibber_exporter user
  ansible.builtin.user:
    name: "{{ tibber_exporter_system_user }}"
    groups: "{{ tibber_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: tibber_exporter_system_user != "root"

- name: Get binary
  when:
    - tibber_exporter_binary_local_dir | length == 0
    - not tibber_exporter_skip_install
  block:

    - name: Download tibber_exporter binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ tibber_exporter_binary_url }}"
        dest: "{{ tibber_exporter_archive_path }}/tibber_exporter-{{ tibber_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack tibber_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "{{ tibber_exporter_archive_path }}/tibber_exporter-{{ tibber_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "{{ tibber_exporter_archive_path }}"
        creates: "{{ tibber_exporter_archive_path }}/tibber_exporter-{{ tibber_exporter_version }}.linux-{{ go_arch }}/tibber_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate tibber_exporter binaries
      ansible.builtin.copy:
        src: "{{ tibber_exporter_archive_path }}/tibber-exporter"
        dest: "{{ tibber_exporter_binary_install_dir }}/tibber_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart tibber_exporter
      when: not ansible_check_mode

- name: Propagate locally distributed tibber_exporter binary
  ansible.builtin.copy:
    src: "{{ tibber_exporter_binary_local_dir }}/tibber_exporter"
    dest: "{{ tibber_exporter_binary_install_dir }}/tibber_exporter"
    mode: 0755
    owner: root
    group: root
  when:
    - tibber_exporter_binary_local_dir | length > 0
    - not tibber_exporter_skip_install
  notify: restart tibber_exporter
